### ISSUE TITLE
keep getting uninitialized @@mtimes on jekyll versions above 3.1.6

### ISSUE THREAD

**Issue by jericbryledy** [zroger/jekyll-minimagick#12]
jekyll 3.2.1 | Error:  uninitialized class variable @@mtimes in Jekyll::JekyllMinimagick::GeneratedImageFile

**Comment by ellioseven** [comment]
+1

**Comment by jericbryledy** [comment]
I think this is what's causing the problem: https://github.com/jekyll/jekyll/commit/7a933893dbcaf1b57dbfafd6dc41edaadef43197

**Comment by jp26jp** [comment]
+1

**Comment by franzos** [comment]
Here's how you can temporarily fix the issue:

1. Open jekyll-minimagick.rb
2. Find "@@mtimes[path] = mtime" around line 43
3. Replace with "self.class.mtimes[path] = mtime"
4. Run Jekyll and enjoy!

If you have no idea where to find the file, use "gem env" to figure out the "GEM PATHS". On MacOS, the full path will look something like this: "/Users/[USERNAME]/.rvm/gems/ruby-2.1.1/gems/jekyll-minimagick-0.0.3/lib"

PS: I've posted a gist with the fix [here](https://gist.github.com/franzos/7d413c0444cbd8b6e25b548ecf6a3a94).

**Comment by salusinarduis** [comment]
Issue still present, proposed franzos fix to the file.

**Comment by zroger** [comment]
Fixed by #13.
